document.writeln("  <div class=\" modal fade\"  id=\"loginpage\">");
document.writeln("		 <div class=\"modal-dialog\">");
document.writeln("    <div class=\"modal-content login-account\">");
document.writeln("		 ");
document.writeln("		<div class=\"close\">");
document.writeln("			<button type=\"button\" class=\"close\" data-dismiss=\"modal\" ><img src=\"images/close-btn.png\" width=\"20\" height=\"20\" alt=\"\"/></button>");
document.writeln("		  </div>");
document.writeln("	    <div class=\"login-logo\"><img src=\"images/GFi-Logo-2.png\" width=\"120\" height=\"137\" alt=\"\"/></div>");
document.writeln("		  <div class=\"login-head\">選擇註冊/登入方式</div>");
document.writeln("	    <button class=\"google\">          ");
document.writeln("			<div class=\"account-icon\"><img src=\"images/google.png\" width=\"35\" height=\"22\" alt=\"\"/></div>");
document.writeln("			使用 Google 帳號登入/註冊</button>");
document.writeln("		 <button class=\"facebook\">");
document.writeln("			<div class=\"account-icon\"><img src=\"images/facebook.png\" width=\"35\" height=\"22\" alt=\"\"/></div>");
document.writeln("			使用 Facebook 帳號登入/註冊</button>");
document.writeln("		  <button class=\"discord\">");
document.writeln("			<div class=\"account-icon\"><img src=\"images/discord.png\" width=\"35\" height=\"22\" alt=\"\"/></div>    ");
document.writeln("			使用 Discord 帳號登入/註冊</button>");
document.writeln("		  <button class=\"apple\">");
document.writeln("			<div class=\"account-icon\"><img src=\"images/apple.png\" width=\"35\" height=\"22\" alt=\"\"/></div>");
document.writeln("			使用 Apple ID 帳號登入/註冊</button>");
document.writeln("		");
document.writeln("	    <div class=\"agree-policy\">");
document.writeln("	      <p>當您按下以上任一個登入按鈕<br>");
document.writeln("");
document.writeln("	      表示您同意平台的 <a href=\"#\">使用者條款</a> 和 <a href=\"#\">隱私權政策</a></p>");
document.writeln("	    </div>");
document.writeln("	    </div>");
document.writeln("		 </div>");
document.writeln("	  </div>");
document.writeln("  <nav class=\"navbar fixed-top navbar-expand-lg navbar-light navbar-bg\" data-aos=\"fade\"> <a class=\"navbar-brand\" href=\"#\"><img src=\"images/GFi-Logo.png\" width=\"88\" height=\"35\" alt=\"\"/></a>  <!--data-aos=\"fade-down\"-->");
document.writeln("    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent1\" aria-controls=\"navbarSupportedContent1\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"> <span class=\"navbar-toggler-icon\"></span> </button>");
document.writeln("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent1\">");
document.writeln("      <ul class=\"navbar-nav mr-auto\">");
document.writeln("        <li class=\"nav-item active\"> <a class=\"nav-link text-light\" href=\"#\">遊戲 <span class=\"sr-only\">(current)</span></a> </li>");
document.writeln("        <li class=\"nav-item\"> <a class=\"nav-link text-light\" href=\"#\">交易</a> </li>");
document.writeln("        <li class=\"nav-item\"> <a class=\"nav-link text-light \" href=\"#\">任務</a> </li>");
document.writeln("		 <li class=\"nav-item\"> <a class=\"nav-link text-light \" href=\"#\">關於</a> </li>");
document.writeln("      </ul>");
document.writeln("     ");
document.writeln("		");
document.writeln("        <a href=\"#loginpage\">");
document.writeln("	   <button class=\"btn btn-outline-info my-2 my-sm-0 btn-sm\" type=\"info\" data-toggle=\"modal\" data-target=\"#loginpage\">註冊/登入</button>");
document.writeln("	   </a>");
document.writeln("		");
document.writeln("	</div>");
document.writeln("  </nav>  ");